# 服务端口号
server.port: 9911
# 设置服务名
spring.application.name: demo-Y-hello-service

server:
  max-http-header-size: 10485760
  # HTTP编码配置
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  # netty: 
  #   idle-timeout: 120s   # 空闲超时时间，当设置了keep-alive，从wireshark看到一直有探测的包，所以这里设置120秒超时





